### PR TITLE
Change the extension from txt to md, create image to docker

### PR DESCRIPTION
**Pull request by sobrito**
- Change the extension from txt to md (markdown) 
- Create a Dockerfile to build a image using the official Wordpress image
- Create a documentation to use the image in docker-composer with a PostgreSQL database embed and other to use the image in kubernetes with a cluster postgresql ha
- Create the same documentation in English and Portuguese (Brazil)
- Edit the main readme file to link with the documentation from contrib

### CODE REVIEW

**Comment by kevinoid** [comment]
Thanks for creating the docker image and this PR @sobrito.  This project is pretty dead at the moment, so I'm hesitant to take on the maintenance of a Docker image.  Is this something you would like to maintain as a separate project?  I'd be happy to add a link to your project from the readme.

**Comment by sobrito** [comment]
We can do it in two ways:

- I keep the docker image (in my own repository) and I have a link to yours with the plugin credits pg4wp with a link to your project and you with a link to the image where I am going using your project.

- You keep the image and I can help you with the image issue, where you could have your specific implementation.
Your project is very interesting, I would be very happy if it didn't die, or be abandoned and I think that in this new culture of kubernetes its implementation would be very welcome (and maintenance would be needed, I wasn't creating some tables), I intend to help as far as possible with both bug fixes and images, but I don't have your knowledge of your plugin or wordpress. (I prefer this option)

Shall we revive your project together?

**Comment by kevinoid** [comment]
Thanks @sobrito, that's a very kind offer!

I think maintaining the Docker image as a separate project (your first option) makes sense organizationally.

If you'd also like to help with this project, that would be great!  I'll send you an invite shortly.  You are welcome to contribute whatever features or bug fixes you'd like.

Don't feel obligated to maintain it.  I think the current implementation (which just does a bunch of regular expression substitutions on the SQL - which were written by the previous maintainer/creator) is fragile and unsustainable.  There are several known issues in the bug tracker.  A better approach might be to parse and transform the SQL, although that has limitations as well.  Unfortunately, it would likely require a lot of work to implement.  Since I'm not currently using Wordpress, I may not get around to it soon.

**Comment by mattbucci** [comment]
Thanks for contributing, but I'm closing this PR as I think maintaining a docker image with a wordpress version is a maintenance burden which should be outside the scope of this project.

**Pull request closed without merging**
