### PR TITLE
Removed the eval, and fixed the p4wp_connstr

### PR DESCRIPTION
**Pull request by ddimitriou**
As discussed in the WP forum.

I strongly suggest we should get rid of the replace and eval crap.

I know that this is subject to change from the original file (wp-db.php) but seriously, replacing code and evaluating on the fly is a very very very bad move.

### CODE REVIEW

**Comment by kevinoid** [comment]
Hi @ddimitriou.

It's unfortunate that you had to go through the effort of reproducing some of the changes for Wordpress 4 support, which you mentioned on the WP forum.  I had hoped the maintainer would include these fixes so others wouldn't need to find it themselves, but no luck yet.  Thanks for taking the effort to separate these changes from the others and send this PR!

This looks good, just a few questions:
- What's the rationale for saving `$GLOBALS['pg4wp_connstr']` in `$pdbconnstr` and conditionally restoring it later?  Why put `$pdbconnstr` in the `wpdb2` class?
- I'm also not a big fan of the current use of `eval`, but it does avoid the maintenance issue of keeping this new `wp-db-pg.php` up to date with `wp-db.php` as changes and fixes are introduced.  I'm not really eager to take on this additional maintenance.  Could you outline the issues you are having which are caused by eval?  You had mentioned the difficulty of debugging through it, which seems unavoidable with eval'd code (although causing your debugger to crash seems like an error the debugger maintainer should fix).  What other issues do you foresee that makes it "very very very bad"?

One other thought, which is a bit of a nitpick, is that I'd prefer if dead code were removed rather than commented out.  It tends to be misleading and add clutter without providing much value beyond the git history.

I'll take a closer look at this soon.  In particular, I'm wondering if it might be possible for a `wpdb2` class to subclass `wpdb` and override only some of the methods while avoiding a lot of the code redundancy and extra maintenance that wholesale copying incurs.  (It may or may not be.)

Thanks again for the PR,
Kevin

**Comment by ddimitriou** [comment]
Hello @kevinoid !!! :)

Yes you are right. I was trying to fix the `@@SESSION` of MySQL equivalent of Postgres and the connection string was lost during the `wpsql_connect` call. I'm sorry about that, I'll remove the `$GLOBALS['pg4wp_connstr']` part.

About eval : http://blogs.msdn.com/b/ericlippert/archive/2003/11/01/53329.aspx

About debugging eval, I honestly do not know how. Especially in this case where the object changes radically ( from `wpdb` to `wpdb2`). The fact that debugger crashed is the least of my problem...

Lastly, I will refactor it the way you are suggesting. Create an extended class, and maybe overriding the functions (if applicable).

I'll keep you posted !

Dimitris

**Comment by kevinoid** [comment]
Sounds good for the `$GLOBALS['pg4wp_connstr']` and `$pdbconnstr`.  Easy enough to clean those out.

In the blog post you linked, Eric Lippert argued that eval is worse due to debugability, maintainability, speed, and memory.  I agree about debugability.  In this case I think the more maintainable solution, by far, is using eval.  And in this case the speed and memory will be equivalent, since the PHP compiler is called to either compile a file or to compile a string (although there may be advantages to file-based sources for pre-compilation or other implementation details).  I don't think this post strongly supports the argument to avoid using eval in this case.

I generally dislike eval and try to avoid it where possible, so I'm not unsympathetic to the argument to remove it.  But I'm still not certain whether it is the right decision in this case.  The subclassed `wpdb2` implementation should make it clearer how much of a maintenance tradeoff we are making.  So we can decide after taking a look at it.

Thanks for the feedback and willingness to work on the PR further.  Don't feel obligated to write the `wpdb2` class just because of my ponderings about it.  If you are interested in exploring it, that's great!  It will certainly save me a lot of effort.  But if you are just concerned about the getting rid of the eval, I may accept the PR as-is if the tradeoff is worth it (or I may take on the burden of proving it's not necessary by writing a subclassed version myself).

Thanks again!  Do keep me posted on how it goes!

**Comment by garak** [comment]
Any news about this?

**Comment by kevinoid** [comment]
I wrote a partial implementation of a proper subclass of `wpdb`, but it required a lot of code to be duplicated from `wp-db.php` shipped with Wordpress.  `wpdb` provides a better API to implement than the MySQL API functions, but I don't think it's worth the additional maintenance burden of adopting all of the duplicated code.

I think the correct solution long-term is to work with the Wordpress maintainers to refactor the `wbdp` class to make it possible to subclass for SQL databases without a lot of code duplication.  So I still consider this an issue, but it'll take some concerted work to address.

**Comment by ddimitriou** [comment]
Apologies for the late response but I was rather busy as well,

@kevinoid is right after all. Using legacy versions of `PHP` there is no alternate way to overload the `wpdb` functions while having a more static file for the `postgres` integration.

I did try to refactor it, just as we discussed in the past but I cannot (without using `namespaces`) overload the functions of the existing implementation so as to decorate them with our own plugin calls (where the actual rewriting of the queries happens).

So unfortunately I will close the PR since the drawback from maintenance is huge, unless there is an update on the php version, where we can reopen it.

**Pull request closed without merging**
