### PR TITLE
Works under WordPress 6.2

### LINKED ISSUE #25: WordPress 6.2 is not supported
I just tested your software, trying to get upgraded to 6.2.

No ball.

Looks like WordPress are bringing [their own DB abstractions](https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wpdb.php) and an unfunny adventure to rewrite 4k lines of code is looking as bright as ever :)

I'm sticking to 5.8. These were the  error messages: 
image

### PR DESCRIPTION
**Pull request by piotrmaslanka**
Without any major mishaps. Had to silence errors, since sometimes  they fail.

image

My blog is the major example that it works - https://henrietta.com.pl
Admin panel works as well. We' ve done it!

Besides @kevinoid the way you approached the problem, this is a way I really like :)

Fixes #25

### CODE REVIEW

**Comment by Verequies** [comment]
Just tried this on my server, but brings me to the installation page every time. What PostgreSQL and PHP versions are you using?

**Comment by piotrmaslanka** [comment]
I've upgraded my WordPress 5.8 to 6.2 with this, so apparently you can't start off fresh, you need to have a working instance.
I'm using PostgreSQL 12-6.1 and PHP 7.4.33.

I haven't tested it with fresh installs, I was just  happy to have a working WordPress 6.2 with PgSQL.

**Comment by Verequies** [comment]
Yeah, that is great you got it working. Unfortunately there seems to be more issues when running WordPress 6.2 with PHP 8.2 and PostgreSQL 15. Was working with PostgreSQL for the most part but since the PHP 8.2 update it is broken. Unable to get it working so will have to move to a different platform than WordPress.

**Comment by tamama** [comment]
Nope. This is not working.

- Postgres 15.2.      (tar.gz)
- PHP 8.0.               (RockyLinux 9 / system).      - php + php-fpm
- Wordpress 6.2.2  (tar.gz)

After patching the obvious (wp-db.php => class-wpdb.php), this generates other issues.

One question though for @kevinoid -- why wouldn't Wordpress adopt Postgres as one of its standard? Since we occupy roughly 20% market share in terms of popularity? 

MySQL remains the de-facto choice - I dont disagree because it occupies roughly 45%. ...

For myself, it is unfortunate - because I have to maintain one more ecosystem (MySQL + UI) for Wordpress .. :(

**Comment by tamama** [comment]
I believe that the more correct design (with minimal maintainance effort) would be:
- Wordpress > MySQL.  (minimal friction, maintainance cost. - as it is always supported by standard)
- Debezium. (Sync from MySQL -> Postgres)
- Then enterprise applications can work with that Postgres RO-replica instead.  (since we always need that RO-replica for load-balancing whole tons of other passive applications)

**Comment by mattbucci** [comment]
I was able to get both installation and blog + content creation working fine on WP Version 6.3.2

I needed to make substantial changes but this plugin was a good start
https://github.com/kevinoid/postgresql-for-wordpress/pull/31

**Comment by tamama** [comment]
@mattbucci 
- I think the bigger problem here is that the base plugin (https://wordpress.org/plugins/postgresql-for-wordpress/) has been dead for quite a long time.
- My 2 cents is to stay away from this mess, otherwise you need to patch-fix for every (few) WP version upgrade(s)
- My gut feeling is that this would get more and more divergent from WP core.
- Though I must admit that it is quite a nuissance to maintain MySQL just for the WP ecosystem ...

**Comment by mattbucci** [comment]
My use case relies on postgres so I don't really have a choice unless I'm
going to move away from WordPress entirely, so in this case the cost to
adapt WordPress is much cheaper than a rewrite against a different CMS.

What I can say from the many hours I've put in so far though is that WP
itself seems to work fine with this plugin's approach, very little of my
required changes had to do with updates on the WP side.

The issue however comes from how brittle it is to try to rewrite MySQL
queries to postgres using regex.

What would really be needed to do a project like this properly would be a
SQL parser in PHP but I have not come across a modern and well maintained
parser in PHP, ideally the parser would parse MySQL input to an AST and
then output to postgres.

**Comment by tamama** [comment]
@mattbucci 
- Totally understand your pain. :)
- As the saying goes always - there is no free lunch. ... Somehow, somewhere, someone needs to pay the price for this tradeoff ...

**Comment by mattbucci** [comment]
Regarding the AST based approach. This is a good reference
https://tomassetti.me/parsing-sql/

I don't think the PHP community is a good resource for these sort of
parsers, but an implementation of a MySQL server in go using dolt should be
possible, and MySQL and postgresql parsers exist in golang so it should be
possible to create a sort of MySQL to postgresql bridge but I haven't found
any evidence of such a project which seems discouraging.

**Comment by mattbucci** [comment]
merged into v1 and v2 branches

**Pull request closed without merging**
