### PR TITLE
(Draft) Trying to fix BIGINT issues

### PR DESCRIPTION
**Pull request by 0xFEEDC0DE64**
I think we should not only cover BIGINT and not only in CREATE TABLE statements...

but this is for now what fixes my problem with wp-statistics

### CODE REVIEW

**Comment by mattbucci** [comment]
Most of these regexes are already case insensitive.

I think we can just add an "i" to the end of https://github.com/PostgreSQL-For-Wordpress/postgresql-for-wordpress/blob/716db95999756ad94d53733e8ca7787a29c13642/pg4wp/rewriters/CreateTableSQLRewriter.php#L99

This should make this case insensitive and either bigint variation should match

**Review by mattbucci — CHANGES_REQUESTED** [review]
Make regexes match insensitively

**Comment by mattbucci** [comment]
Looks like we have a failing test, but it's the test itself that is incorrect.

```
1) rewriteTest::test_it_removes_character_sets
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
platform varchar(255),
version varchar(255),
location varchar(10),
- user_id BIGINT(48) NOT NULL,
- page_id BIGINT(48) NOT NULL,
+ user_id BIGINT NOT NULL,
+ page_id BIGINT NOT NULL,
```

**Comment by 0xFEEDC0DE64** [comment]
Have you found another solution for this problem?

**Comment by mattbucci** [comment]
See https://github.com/PostgreSQL-For-Wordpress/postgresql-for-wordpress/pull/131

**Pull request closed without merging**
